baseURL = 'http://www.carmeliarose.shop/'
languageCode = 'en-us'
title = 'Kshitij Chandrakar'
theme = 'diary'

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "perldoc"
    tabWidth = 4

[params]
  subtitle = 'By Carmelia Rose'
  enableGitalk = false
  enableGiscus = false


[taxonomies]
   tag = "tags"
   category = "categories"

[[menu.main]]
url = "/recipes"
name = "Recipes"
weight = 2
[[menu.main]]
url = "/projects"
name = "Projects"
weight = 3
[[menu.main]]
url = "/posts"
name = "Posts"
weight = 1
